In [9]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

# Slicing 1D Array

In [1]:
nums=[0,1,2,3,4,5]

左闭右开

In [2]:
print(nums[0:5])
print(nums[:])
print(nums[2:])
print(nums[:2])
print(nums[:-1])

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[2, 3, 4, 5]
[0, 1]
[0, 1, 2, 3, 4]


In [4]:
nums[2:4]=[4,6]
print(nums)

[0, 1, 4, 6, 5]


# Slicing 2D Array

In [8]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b.shape)
print(b.ndim)

print(b[:,0])
print(b[0,:])

print(b[-1])
print(b[-1,:])
print(b[-1,...])

print(b[0:2,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
[1 5 9]
[1 2 3 4]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[[1 2 3 4]
 [5 6 7 8]]


# Loading Data From .csv File

In [11]:
xy=np.loadtxt('data-01-test-score.csv',delimiter=',',dtype=np.float32)
x_data=xy[:,0:-1]
y_data=xy[:,[-1]] 

print(x_data)
print(x_data.shape)
print(len(x_data))
print(x_data[:5])

print(y_data)
print(y_data.shape)
print(len(y_data))
print(y_data[:5])

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
(5, 3)
5
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]
(5, 1)
5
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


对比于y_data=xy[ : , -1 ] , y_data=xy[ : , [ -1 ] ]可保留为二维

# Low-Level Implementation 

In [ ]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

W=torch.zeros((3,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=1e-5)

nb_epochs=20
for epoch in range(nb_epochs+1):
    
    hypothesis=x_train.matmul(W)+b
    
    cost=torch.mean((hypothesis-y_train)**2)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch{:4d}/{} Cost:{:.6f}'.format(
        epoch,nb_epochs,cost.item()
    ))

# High-Level Implementation

In [13]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,1)
        
    def forward(self,x):
        return self.linear(x)

In [15]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

model=MultivariateLinearRegressionModel()

optimizer=optim.SGD(model.parameters(),lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    prediction=model(x_train)
    
    cost=F.mse_loss(prediction,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 39633.414062
Epoch    1/20 Cost: 12431.273438
Epoch    2/20 Cost: 3904.840332
Epoch    3/20 Cost: 1232.251709
Epoch    4/20 Cost: 394.532684
Epoch    5/20 Cost: 131.948273
Epoch    6/20 Cost: 49.637566
Epoch    7/20 Cost: 23.833128
Epoch    8/20 Cost: 15.740547
Epoch    9/20 Cost: 13.199559
Epoch   10/20 Cost: 12.398743
Epoch   11/20 Cost: 12.143396
Epoch   12/20 Cost: 12.059056
Epoch   13/20 Cost: 12.028257
Epoch   14/20 Cost: 12.014270
Epoch   15/20 Cost: 12.005560
Epoch   16/20 Cost: 11.998510
Epoch   17/20 Cost: 11.991979
Epoch   18/20 Cost: 11.985615
Epoch   19/20 Cost: 11.979303
Epoch   20/20 Cost: 11.973015
