In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np

In [2]:
torch.manual_seed(1)

In [3]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [4]:
x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)
print(x_train.shape)
print(y_train.size())

torch.Size([6, 2])
torch.Size([6, 1])


In [5]:
print(torch.exp(torch.FloatTensor([1])))#equals e^1
print(torch.sigmoid(torch.FloatTensor([1])))#equals 1/(1+e^-1)

tensor([2.7183])
tensor([0.7311])


In [6]:
W=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

torch.exp()

In [7]:
hypothesis=1/(1+torch.exp(-(x_train.matmul(W)+b)))
print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


torch.sigmoid

In [8]:
hypothesis=torch.sigmoid(x_train.matmul(W)+b)
print(hypothesis)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)


In [9]:
losses_1=-(y_train[0]*torch.log(hypothesis[0]))+(1-y_train[0])*torch.log(1-hypothesis[0])
print(losses_1)
losses=-(y_train*torch.log(hypothesis))+(1-y_train)*torch.log(1-hypothesis)
print(losses)

tensor([-0.6931], grad_fn=<AddBackward0>)
tensor([[-0.6931],
        [-0.6931],
        [-0.6931],
        [ 0.6931],
        [ 0.6931],
        [ 0.6931]], grad_fn=<AddBackward0>)


In [10]:
cost = losses.mean()
cost_1=losses.mean(dim=0)
print(cost_1)
print(cost)

tensor([0.], grad_fn=<MeanBackward1>)
tensor(0., grad_fn=<MeanBackward0>)


In [11]:
F.binary_cross_entropy(hypothesis,y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

1

In [ ]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [ ]:
print(x_train[0:5])
print(y_train[0:5])

In [ ]:
W=torch.randn([8,1],requires_grad=True)
b=torch.randn(1,requires_grad=True)
optimizer=optim.Adam([W,b],lr=1)
nb_epochs=100
for epoch in range(nb_epochs+1):
    hypothesis=torch.sigmoid(x_train.matmul(W)+b)
    cost=F.binary_cross_entropy(hypothesis,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%10==0:
        print("Epoch:{:4d}/{}Cost:{:.6f}".format(
            epoch,nb_epochs,cost.item()
        ))

In [ ]:
hypothesis=torch.sigmoid(x_train.matmul(W)+b)
print(hypothesis[:5])
prediction=hypothesis>=0.5
print(prediction[:5])
correct=prediction.float()==y_train
print(correct[:5])
accuracy=correct.sum().item()/len(correct)
print("accuracy:{:2.2f}%".format(
    accuracy*100
))

2

In [ ]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(8,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,x):
        return self.sigmoid(self.linear(x))

In [ ]:
model=BinaryClassifier()

optimizer=optim.SGD(model.parameters(),lr=1)
nb_epochs=100
for epoch in range(nb_epochs+1):
    hypothesis=model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)


    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 10 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction)
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy {:2.2f}%'.format(
            epoch, nb_epochs, cost.item(), accuracy * 100,
        ))