In [2]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [3]:
torch.manual_seed(1)

In [17]:
z=torch.rand(3,5,requires_grad=True)
hypothesis=F.softmax(z,dim=1)
y=torch.randint(0,5,(3,)).long()
y_one_hot=torch.zeros_like(hypothesis)
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [22]:
torch.log(F.softmax(z,dim=1))


tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward0>)

In [23]:
F.log_softmax(z,dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

In [25]:
(y_one_hot*-torch.log(F.softmax(z,dim=1))).sum(dim=1).mean()

tensor(1.4689, grad_fn=<MeanBackward0>)

In [26]:
F.nll_loss(F.log_softmax(z,dim=1),y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [27]:
F.cross_entropy(z,y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [13]:
xy=np.loadtxt('data-04-zoo.csv',delimiter=',',dtype=np.float32)
x_train=torch.FloatTensor(xy[:,0:-1])
y_train=torch.LongTensor(xy[:,[-1]]).squeeze()

In [10]:
print(x_train.shape)
print(len(x_train))
print(x_train[:5])

torch.Size([101, 16])
101
tensor([[1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 4., 1., 0., 1.],
        [0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 1., 0., 1.]])


In [14]:
print(y_train.shape)
print(len(y_train))
print(y_train[:5])

torch.Size([101])
101
tensor([0, 0, 3, 0, 0])


In [15]:
nb_classes=7
#scatter(dim, index, src)
y_one_hot=torch.zeros((len(y_train),nb_classes))
y_one_hot.scatter_(1,y_train.unsqueeze(1),1)

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0.,

In [16]:
W=torch.zeros((16,7),requires_grad=True)
b=torch.zeros(1,requires_grad=True)
optimizer=optim.SGD([W,b],lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):
    z=x_train.matmul(W)+b
    cost=F.cross_entropy(z,y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    if epoch%100==0:
        print("Epoch:{:4d}/{}Cost:{:.6f}".format(
        epoch,nb_epochs,cost.item()
        ))

Epoch:   0/1000Cost:1.945910
Epoch: 100/1000Cost:0.471836
Epoch: 200/1000Cost:0.326327
Epoch: 300/1000Cost:0.257839
Epoch: 400/1000Cost:0.215762
Epoch: 500/1000Cost:0.186603
Epoch: 600/1000Cost:0.164898
Epoch: 700/1000Cost:0.147955
Epoch: 800/1000Cost:0.134279
Epoch: 900/1000Cost:0.122962
Epoch:1000/1000Cost:0.113422
