In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
z=torch.FloatTensor([1,2,3])

In [3]:
hypothesis=F.softmax(z,dim=0) #一维张量的 dim=0 是直接对所有元素进行 softmax
print(hypothesis)
print(hypothesis.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


In [4]:
t=torch.FloatTensor([[1,2,3],[4,5,6]])
hy_1=F.softmax(t,dim=0)#对 行 进行 softmax（通常用于批量数据）
print(hy_1)
hy_2=F.softmax(t,dim=1)#对 列 进行 softmax（通常用于分类任务的输出层）
print(hy_2)
#数值稳定性,避免溢出
hypothesis=F.softmax(t-t.max(),dim=0)

tensor([[0.0474, 0.0474, 0.0474],
        [0.9526, 0.9526, 0.9526]])
tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])


In [5]:
z=torch.rand([3,5],requires_grad=True)
print(z)
hypothesis=F.softmax(z,dim=1)
print(hypothesis)

tensor([[0.7576, 0.2793, 0.4031, 0.7347, 0.0293],
        [0.7999, 0.3971, 0.7544, 0.5695, 0.4388],
        [0.6387, 0.5247, 0.6826, 0.3051, 0.4635]], requires_grad=True)
tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [6]:
y=torch.randint(0,5,(3,))
print(y)
y_one_hot=torch.zeros_like(hypothesis)
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([0, 2, 1])


tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [7]:
cost=(y_one_hot*-torch.log(hypothesis)).sum(dim=1).mean()#Cross Entropy Loss
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


In [8]:
torch.log(F.softmax(z,dim=1))

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward0>)

In [9]:
F.log_softmax(z,dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

In [10]:
(y_one_hot*-torch.log(F.softmax(z,dim=1))).sum(dim=1).mean()

tensor(1.4689, grad_fn=<MeanBackward0>)

In [11]:
F.nll_loss(F.log_softmax(z,dim=1),y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [12]:
F.cross_entropy(z,y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [13]:
x_data  = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_data  = [2, 2, 2, 1, 1, 1, 0, 0]

x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [14]:
W=torch.zeros((4,3),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

optimizer=optim.SGD([W,b],lr=0.1)

nb_epochs=1000
for epoch in range(nb_epochs+1):
    
    hypothesis=F.softmax(x_train.matmul(W)+b,dim=1)
    
    y_one_hot=torch.zeros_like(hypothesis)
    y_one_hot.scatter_(1,y_train.unsqueeze(1).long(),1)
    
    cost=(y_one_hot*-torch.log(hypothesis)).sum(dim=1).mean()
    
    #z=x_train.matmul(W)+b
    #cost=F.cross_entropy(z,y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch%100==0:
        print("Epoch:{:4d}/{}Cost:{:.6f}".format(
        epoch,nb_epochs,cost.item()
        ))

Epoch:   0/1000Cost:1.098612
Epoch: 100/1000Cost:0.761050
Epoch: 200/1000Cost:0.689991
Epoch: 300/1000Cost:0.643229
Epoch: 400/1000Cost:0.604117
Epoch: 500/1000Cost:0.568255
Epoch: 600/1000Cost:0.533922
Epoch: 700/1000Cost:0.500291
Epoch: 800/1000Cost:0.466908
Epoch: 900/1000Cost:0.433507
Epoch:1000/1000Cost:0.399962
